name: Generate Static Content

on:
  push:
    branches:
      - main # o el nombre de tu rama principal
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Generate static content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p public/content
          for file in content/*.md; do
            filename=$(basename "$file")
            content=$(python -c "import sys, json, base64; print(json.dumps({'content': base64.b64encode(sys.stdin.read().encode('utf-8')).decode('utf-8')}))" < "$file")
            echo "$content" > "public/content/${filename%.md}.json"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
